management:
  security:
    enabled: false

spring:
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail_on_empty_beans: false
      indent_output: true